repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-json
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.28.3
    hooks:
      - id: check-jsonschema
        files: ^renovate\.json$
        args: [ "--check-metaschema" ]
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.58.0
    hooks:
      - id: golangci-lint